apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-app
  namespace: music-app
  labels:
    app: music-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: music-app
  template:
    metadata:
      labels:
        app: music-app
    spec:
      containers:
        - name: music-app
          image: music-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password
          args:
            - "redis:6379"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /api/v1/music-albums?key=100
              port: 9090
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/music-albums?key=100
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 30
