apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: music-ingress
  namespace: music-app
spec:
  tls:
  - hosts:
    - music.local
    secretName: music-tls
  rules:
  - host: music.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: music-app
            port:
              number: 9090
